module.exports = {
	'/avtm/getIndexBanner':{
        target:'http://localhost:8181/',
        changeOrigin:true,
        pathRewrite:{
            '^/avtm/getIndexBanner':'/data/index/getIndexBanner.json'
        }
    },
    '/avtm/getIndexCategoryNav':{
        target:'http://localhost:8181/',
        changeOrigin:true,
        pathRewrite:{
            '^/avtm/getIndexCategoryNav':'/data/index/getIndexCategoryNav.json'
        }
    },
    '/avtm/getMarketingPic':{
        target:'http://localhost:8181/',
        changeOrigin:true,
        pathRewrite:{
            '^/avtm/getMarketingPic':'/data/index/getMarketingPic.json'
        }
    },
    '/discount/getIndexDiscount':{
        target:'http://localhost:8181/',
        changeOrigin:true,
        pathRewrite:{
            '^/discount/getIndexDiscount':'/data/index/getIndexDiscount.json'
        }
    },
    '/avtm/getIndexRecommend':{
        target:'http://localhost:8181/',
        changeOrigin:true,
        pathRewrite:{
            '^/avtm/getIndexRecommend':'/data/index/getIndexRecommend.json'
        }
    },
    '/avtm/getIndexTexts':{
        target:'http://localhost:8181/',
        changeOrigin:true,
        pathRewrite:{
            '^/avtm/getIndexTexts':'/data/index/getIndexTexts.json'
        }
    },
    '/avtm/getIndexColumn':{
        target:'http://localhost:8181/',
        changeOrigin:true,
        pathRewrite:{
            '^/avtm/getIndexColumn':'/data/index/getIndexColumn.json'
        }
    },
    '/avtm/getPromotoPic':{
        target:'http://localhost:8181/',
        changeOrigin:true,
        pathRewrite:{
            '^/avtm/getPromotoPic':'/data/index/getPromotoPic.json'

        }
    },
    '/user/userTips':{
        target:'http://localhost:8181/',
        changeOrigin:true,
        pathRewrite:{
            '^/user/userTips':'/data/index/userTips.json'

        }
    }
}